<?php if (isset($subscriber)) {?>
<strong>Subscriber&rsquo;s profile:</strong><br />
<table class="table table-stripeds table-bordered" width="50%" border="1" cellspacing="0" style="border:1px solid #dddddd;border-collapse:collapse;">
	<tbody>
		<tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Phone number</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo ((isset($subscriber['Subscriber_Info']['PhoneNo']))? $subscriber['Subscriber_Info']['PhoneNo'] : '');?></td></tr>
		<tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">SIM ID</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($subscriber['Subscriber_Info']['ICCID']))? $subscriber['Subscriber_Info']['ICCID']:'';?></td></tr>
		<tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Subscription date</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($subscriber['Subscriber_Info']['EffectiveDate']))? date("d-M-Y", strtotime($subscriber['Subscriber_Info']['EffectiveDate'])):'';?></td></tr>
		<tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Status</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($subscriber['Subscriber_Info']['SubStatus']))? $subscriber['Subscriber_Info']['SubStatus']:'';?></td></tr>
		<tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Outstanding Bill</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($subscriber['Balance_info']['OutStandingAmount']))? $subscriber['Balance_info']['OutStandingAmount']:'0';?> USD</td></tr>
		<tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Total Credit Amount</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($subscriber['Balance_info']['TotalCreditAmount']))? $subscriber['Balance_info']['TotalCreditAmount']:'0';?> USD</td></tr>
		<tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Available Credit Amount</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($subscriber['Balance_info']['TotalRemainAmount']))? $subscriber['Balance_info']['TotalRemainAmount']:'0';?> USD</td></tr>
		<tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Tariff</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($subscriber['Tariff_Info']['OfferingName']))? $subscriber['Tariff_Info']['OfferingName']:'';?></td></tr>
		<tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Tariff Activation Date</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($subscriber['Tariff_Info']['EffectiveDate']))? date('d-M-Y', strtotime($subscriber['Tariff_Info']['EffectiveDate'])):'';?></td></tr>
		<tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Services</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;">
			<?php if (isset($subscriber['Service_Info'])) {
					echo implode('<br />', $subscriber['Service_Info']);
			}?></td></tr>
     </tbody>
</table>
<?php } //end if table?>

<?php if (isset($customer)) {?>
<strong>Customer&rsquo;s profile:</strong><br />
<table class="table table-stripeds table-bordered" width="50%" border="1" cellspacing="0" style="border:1px solid #dddddd;border-collapse:collapse;">
	<tbody>
		  <tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Corporate Name</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo ((isset($customer['CustName']))? $customer['CustName'] : '');?></td></tr>
          <tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Industry</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($customer['IndustryName']))? $customer['IndustryName']:'';?></td></tr>
          <tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Account Status</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($customer['CustStatus'])? $customer['CustStatus']:'');?></td></tr>
          <tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Billing Medium</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($customer['BillMediumCode']))? Customer_model::$BillMediumCode[$customer['BillMediumCode']] . ' Bill': '';?></td></tr>
          <tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Bill due Date</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($customer['DueDate']))? $customer['DueDate']: '';?></td></tr>
          <tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Bill Statement Date</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($customer['BillCycleType']))? $customer['BillCycleType']: '';?></td></tr>
          <tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Contract Date</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo ((isset($customer['RegisterDate']))? date('d-M-Y', strtotime($customer['RegisterDate'])): '');?></td></tr>
          <tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Passport</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($customer['passport']))? $customer['passport']: '';?></td></tr>
          <tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;"><?php echo label('lbl_card_id')?></td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($customer['card_id']))? $customer['card_id']: '';?></td></tr>
          <tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Certificate #</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($customer['CertificateNumId']))? $customer['CertificateNumId']: '';?></td></tr>
          <tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">TIN</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($customer['tin']))? $customer['tin']: '';?></td></tr>
          <tr><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;text-align:right;padding-right:10px;">Agreement Number</td><td style="border:1px solid #dddddd;border-collapse:collapse;width:50%;padding-left:10px;"><?php echo (isset($customer['AgreementId']))? $customer['AgreementId']: '';?></td></tr>
     </tbody>
</table>
<?php } //end if table?>